document.writeln("<!DOCTYPE html>");
document.writeln("<html class=\'no-js\' lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <!-- footer -->");
document.writeln("    <footer class=\'footer\'>");
document.writeln("        <h3>Stay connected with me</h3>");
document.writeln("        <div class=\'container footer-bot\'>");
document.writeln("            <div class=\'row\'>");
document.writeln("                <!-- logo -->");
document.writeln("                <div class=\'col-xs-12 col-sm-6 col-md-3 col-lg-3\'>");
document.writeln("                    <img src=\'../images/footer-logo.png\' style=\'width: 100px;height: auto;\' alt=\'Kai Ren\' title=\'Kai Ren\' />");
document.writeln("                    <p class=\'copy-right\'>");
document.writeln("                        <a style=\'display:inline-block;text-decoration:none;height:20px;line-height:20px;\'");
document.writeln("                            href=\'http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=61909002000104\'");
document.writeln("                            target=\'_blank\'><img src=\'../images/beian.png\' style=\'width: auto;float: left;\' />&nbsp;陕公网安备");
document.writeln("                            61909002000104号</a>");
document.writeln("                    </p>");
document.writeln("                    <p style=\'margin: 0px;\'>");
document.writeln("                        &nbsp;&nbsp;&copy; Reserved Kai Ren inc 2018-<span id=\'currentYear\'></span>.");
document.writeln("                    </p>");
document.writeln("                </div>");
document.writeln("                <!-- logo -->");
document.writeln("");
document.writeln("                <!-- address -->");
document.writeln("                <div class=\'col-xs-12 col-sm-6 col-md-3 col-lg-3 padding-top\'>");
document.writeln("                    <address>");
document.writeln("                        <p></p>");
document.writeln("                        <p id=\'mySchool\'></p>");
document.writeln("                        <p id=\'myCollege\'></p>");
document.writeln("                    </address>");
document.writeln("                </div>");
document.writeln("                <!-- address -->");
document.writeln("");
document.writeln("                <!-- email -->");
document.writeln("                <div class=\'col-xs-12 col-sm-6 col-md-3 col-lg-3 padding-top\'>");
document.writeln("                    <p></p>");
document.writeln("                    <p id=\'myEmail\'></p>");
document.writeln("                    <p id=\'myEmail2\'></p>");
document.writeln("                </div>");
document.writeln("                <!-- email -->");
document.writeln("");
document.writeln("                <!-- social -->");
document.writeln("                <div class=\'col-xs-12 col-sm-6 col-md-3 col-lg-3 padding-top\'>");
document.writeln("                    <p></p>");
document.writeln("                    <ul class=\'social\'>");
document.writeln("                        <li><a href=\'https://github.com/renkaigis\'><i class=\'fa fa-github\'></i></a></li>");
document.writeln("                        <li><a href=\'https://weibo.com/renkai123\'><i class=\'fa fa-weibo\'></i></a></li>");
document.writeln("                        <li><a href=\'https://twitter.com/renkaigis\'><i class=\'fa fa-twitter\'></i></a></li>");
document.writeln("                        <li><a href=\'mailto:renkaigis@gmail.com\'><i class=\'fa fa-envelope\'></i></a></li>");
document.writeln("                    </ul>");
document.writeln("                    <p class=\'made-by\'>Made with by <i class=\'fa fa-heart\' aria-hidden=\'true\'></i> <a");
document.writeln("                            href=\'https://www.renkaigis.cn\' target=\'_blank\'>Kai Ren</a>");
document.writeln("                        <p>");
document.writeln("                </div>");
document.writeln("                <!-- social -->");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </footer>");
document.writeln("    <!-- footer -->");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");


// 20220301备份
// document.writeln("<!DOCTYPE html>");
// document.writeln("<html class=\'no-js\' lang=\'en\'>");
// document.writeln("");
// document.writeln("<head>");
// document.writeln("");
// document.writeln("    <meta charset=\'utf-8\'>");
// document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
// document.writeln("    <meta name=\'viewport\' content=\'initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no\'>");
// document.writeln("    <link rel=\'shortcut icon\' href=\'../images/favicon.ico\' type=\'image/x-icon\'>");
// document.writeln("    <title>Photo - 国庆拍国旗</title>");
// document.writeln("");
// document.writeln("");
// document.writeln("    <!-- Normalize -->");
// document.writeln("    <link rel=\'stylesheet\' href=\'../css/assets/normalize.css\' type=\'text/css\'>");
// document.writeln("    <!-- Bootstrap -->");
// document.writeln("    <link href=\'../css/assets/bootstrap.min.css\' rel=\'stylesheet\' type=\'text/css\'>");
// document.writeln("    <!-- Font-awesome.min -->");
// document.writeln("    <link href=\'../css/font-awesome.min.css\' rel=\'stylesheet\' type=\'text/css\'>");
// document.writeln("    <!-- Main Style -->");
// document.writeln("    <link rel=\'stylesheet\' href=\'../css/main.css\' type=\'text/css\'>");
// document.writeln("    <!-- Responsive Style -->");
// document.writeln("    <link href=\'../css/responsive.css\' rel=\'stylesheet\' type=\'text/css\'>");
// document.writeln("    <!-- MyStyle -->");
// document.writeln("    <link href=\'../css/mystyle.css\' rel=\'stylesheet\' type=\'text/css\'>");
// document.writeln("");
// document.writeln("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->");
// document.writeln("    <!--[if lt IE 9]>");
// document.writeln("      <script src=\'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\'></script>");
// document.writeln("      <script src=\'https://oss.maxcdn.com/respond/1.4.2/respond.min.js\'></script>");
// document.writeln("    <![endif]-->");
// document.writeln("");
// document.writeln("    <!-- 返回顶部 -->");
// document.writeln("    <link href=\'../css/backtop.css\' rel=\'stylesheet\' type=\'text/css\' />");
// document.writeln("");
// document.writeln("    <script src=\'../js/jquery1.7.min.js\' type=\'text/javascript\'></script>");
// document.writeln("");
// document.writeln("    <script src=\'../js/assets/modernizr-2.8.3.min.js\' type=\'text/javascript\'></script>");
// document.writeln("");
// document.writeln("");
// document.writeln("</head>");
// document.writeln("");
// document.writeln("<body>");
// document.writeln("    <!-- footer -->");
// document.writeln("    <footer class=\'footer\'>");
// document.writeln("        <h3>Stay connected with me</h3>");
// document.writeln("        <div class=\'container footer-bot\'>");
// document.writeln("            <div class=\'row\'>");
// document.writeln("                <!-- logo -->");
// document.writeln("                <div class=\'col-xs-12 col-sm-6 col-md-3 col-lg-3\'>");
// document.writeln("                    <img src=\'../images/footer-logo.png\' style=\'width: 100px;height: auto;\' alt=\'Kai Ren\' title=\'Kai Ren\' />");
// document.writeln("                    <p class=\'copy-right\' style=\'margin: 0px 0px 5px 0px;\'>");
// document.writeln("                        <a href=\'https://beian.miit.gov.cn/\' target=\'_blank\'>陕ICP备17015858号</a>");
// document.writeln("                    </p>");
// document.writeln("                    <p style=\'margin: 0px;\'>");
// document.writeln("                        &copy; Reserved Kai Ren inc 2018-<span id=\'currentYear\'></span>.");
// document.writeln("                    </p>");
// document.writeln("                </div>");
// document.writeln("                <!-- logo -->");
// document.writeln("                <!-- address -->");
// document.writeln("                <div class=\'col-xs-12 col-sm-6 col-md-3 col-lg-3 padding-top\'>");
// document.writeln("                    <address>");
// document.writeln("                        <p id=\'mySchool\'></p>");
// document.writeln("                        <p id=\'myCollege\'></p>");
// document.writeln("                    </address>");
// document.writeln("                </div>");
// document.writeln("                <!-- address -->");
// document.writeln("                <!-- email -->");
// document.writeln("                <div class=\'col-xs-12 col-sm-6 col-md-3 col-lg-3 padding-top\'>");
// document.writeln("                    <p id=\'myEmail\'></p>");
// document.writeln("                    <p id=\'myQQ\'></p>");
// document.writeln("                </div>");
// document.writeln("                <!-- email -->");
// document.writeln("                <!-- social -->");
// document.writeln("                <div class=\'col-xs-12 col-sm-6 col-md-3 col-lg-3 padding-top\'>");
// document.writeln("                    <ul class=\'social\'>");
// document.writeln("                        <li><a href=\'https://github.com/renkaigis\'><i class=\'fa fa-github\'></i></a></li>");
// document.writeln("                        <li><a href=\'https://weibo.com/renkai123\'><i class=\'fa fa-weibo\'></i></a></li>");
// document.writeln("                        <li><a href=\'https://www.facebook.com/renkaigis\'><i class=\'fa fa-facebook\'></i></a></li>");
// document.writeln("                        <li><a href=\'mailto:renkaigis@gmail.com\'><i class=\'fa fa-envelope\'></i></a></li>");
// document.writeln("                    </ul>");
// document.writeln("                    <p class=\'made-by\'>Made with by <i class=\'fa fa-heart\' aria-hidden=\'true\'></i> <a");
// document.writeln("                            href=\'http://www.renkaigis.com\' target=\'_blank\'>Kai Ren</a>");
// document.writeln("                    <p>");
// document.writeln("                </div>");
// document.writeln("                <!-- social -->");
// document.writeln("            </div>");
// document.writeln("        </div>");
// document.writeln("    </footer>");
// document.writeln("    <!-- footer -->");
// document.writeln("");
// document.writeln("");
// document.writeln("    <!-- jQuery -->");
// document.writeln("    <script type=\'text/javascript\' src=\'../js/backtop.js\'></script>");
// document.writeln("    <a href=\'#0\' class=\'cd-top\'></a>");
// document.writeln("    <script src=\'../js/jquery.min.js\'></script>");
// document.writeln("    <script>window.jQuery || document.write(\'<script src=\'../js/assets/jquery.min.js\'><\/\//script>\')</script>");
// document.writeln("    <script src=\'../js/assets/plugins.js\' type=\'text/javascript\'></script>");
// document.writeln("    <script src=\'../js/assets/bootstrap.min.js\' type=\'text/javascript\'></script>");
// document.writeln("    <script src=\'../js/main.js\' type=\'text/javascript\'></script>");
// document.writeln("    <script src=\'../js/jquery.nicescroll.min.js\' type=\'text/javascript\'></script>");
// document.writeln("    <script src=\'../js/myCustom.js\' type=\'text/javascript\'></script>");
// document.writeln("");
// document.writeln("</body>");
// document.writeln("");
// document.writeln("</html>");